"""pdf_reports.py — Génération des rapports PDF (patient, VINC)."""
from datetime import date

import pandas as pd
from fpdf import FPDF

from business_logic import compute_oor_flag
from db import get_setting, now_utc_iso, read_full_results, read_remarks


def _pdf_header(pdf, company_name, title, subtitle=""):
    pdf.set_fill_color(18, 60, 90)
    pdf.rect(0, 0, pdf.w, 22, style="F")
    pdf.set_text_color(255, 255, 255)
    pdf.set_font("Helvetica", "B", 16)
    pdf.set_xy(10, 6)
    pdf.cell(0, 8, f"{company_name} - {title}", ln=1)
    if subtitle:
        pdf.set_font("Helvetica", "", 10)
        pdf.set_xy(10, 14)
        pdf.cell(0, 6, subtitle, ln=1)
    pdf.set_text_color(27, 38, 49)


def generate_vinc_pdf_report(conn, vinc_df, generated_by):
    company_name = get_setting(conn, "company_name") or "Clinical Services"
    generated_at = now_utc_iso()

    pdf = FPDF(orientation="L", unit="mm", format="A4")
    pdf.add_page()
    pdf.set_auto_page_break(auto=True, margin=15)
    _pdf_header(pdf, company_name, "Study BLOOD", "Monthly VINC extract report")

    pdf.set_xy(10, 28)
    pdf.set_font("Helvetica", "", 9)
    pdf.cell(0, 5, f"Generated by: {generated_by}", ln=1)
    pdf.cell(0, 5, f"Generated at (UTC): {generated_at}", ln=1)
    pdf.cell(0, 5, f"Total VINC results included: {len(vinc_df)}", ln=1)
    pdf.cell(0, 5,
             f"Distinct patients: {vinc_df['usubjid'].nunique() if not vinc_df.empty else 0}",
             ln=1)
    pdf.ln(4)

    headers = ["USUBJID", "Site", "Test", "Value", "Unit", "Ref. range", "Date", "Flag"]
    col_widths = [45, 20, 45, 20, 20, 30, 25, 30]
    pdf.set_font("Helvetica", "B", 8)
    pdf.set_fill_color(18, 60, 90)
    pdf.set_text_color(255, 255, 255)
    for header, width in zip(headers, col_widths):
        pdf.cell(width, 7, header, border=1, align="C", fill=True)
    pdf.ln()

    pdf.set_font("Helvetica", "", 8)
    pdf.set_text_color(27, 38, 49)
    for i, (_, row) in enumerate(vinc_df.iterrows()):
        pdf.set_fill_color(240, 244, 248) if i % 2 == 0 else pdf.set_fill_color(255, 255, 255)
        ref_range = ""
        if pd.notna(row.get("ref_low")) and pd.notna(row.get("ref_high")):
            ref_range = f"{row['ref_low']}-{row['ref_high']}"
        flag = str(row.get("Alerte", ""))
        flag_clean = ("CRITICAL" if "CRITICAL" in flag
                      else ("OUTLIER" if "Outlier" in flag else ("Normal" if flag else "")))
        values = [
            str(row.get("usubjid", "")), str(row.get("site_id", "")),
            str(row.get("test_code", "")), str(row.get("result_value", "")),
            str(row.get("result_unit", "")), ref_range,
            str(row.get("result_date", "")), flag_clean,
        ]
        for val, width in zip(values, col_widths):
            pdf.cell(width, 6, val[:22], border=1, fill=True)
        pdf.ln()

    pdf.ln(6)
    pdf.set_font("Helvetica", "I", 7)
    pdf.set_text_color(120, 130, 140)
    pdf.multi_cell(0, 4, "This PDF generation is itself recorded in the application's "
                          "immutable audit trail, in accordance with 21 CFR Part 11 / Annex 11.")
    return bytes(pdf.output(dest="S"))


def generate_patient_pdf_report(conn, usubjid, generated_by, password=None):
    """Compte-rendu biologique complet pour un patient. Si `password`
    est fourni, le PDF est chiffré (mot de passe utilisateur = lecture,
    mot de passe propriétaire distinct = permissions) — utilisé pour la
    diffusion automatique sécurisée par e-mail (voir automation.py /
    streamlit_app.py, page Biological Validation)."""
    df = read_full_results(conn)
    patient_df = df[df["usubjid"] == usubjid].copy()
    if patient_df.empty:
        return None

    patient_df = compute_oor_flag(patient_df)
    patient_df = patient_df.sort_values(["visit_num", "test_code"])

    company_name = get_setting(conn, "company_name") or "Clinical Services"
    site_name = patient_df.iloc[0]["site_name"]
    country = patient_df.iloc[0]["country"]
    sex = patient_df.iloc[0]["sex"]
    birth_year = patient_df.iloc[0]["birth_year"]
    generated_at = now_utc_iso()

    last_bio_validation = patient_df[patient_df["biologist_validated_by"].notna()]
    validator = (last_bio_validation.iloc[-1]["biologist_validated_by"]
                 if not last_bio_validation.empty else "Pending biological validation")

    pdf = FPDF(orientation="P", unit="mm", format="A4")
    pdf.add_page()
    pdf.set_auto_page_break(auto=True, margin=15)
    _pdf_header(pdf, company_name, "Study BLOOD", "Patient biological report")

    pdf.set_xy(10, 28)
    pdf.set_font("Helvetica", "B", 11)
    pdf.cell(0, 6, f"Patient: {usubjid}", ln=1)
    pdf.set_font("Helvetica", "", 9)
    pdf.cell(0, 5, f"Site: {site_name} ({country})", ln=1)
    pdf.cell(0, 5, f"Sex: {sex} | Birth year: {birth_year}", ln=1)
    pdf.cell(0, 5, f"Generated by: {generated_by} | Generated at (UTC): {generated_at}", ln=1)
    pdf.ln(3)

    headers = ["Visit", "Test", "Value", "Unit", "Ref. range", "Date", "Flag"]
    col_widths = [20, 45, 22, 20, 30, 25, 28]
    pdf.set_font("Helvetica", "B", 8)
    pdf.set_fill_color(18, 60, 90)
    pdf.set_text_color(255, 255, 255)
    for header, width in zip(headers, col_widths):
        pdf.cell(width, 7, header, border=1, align="C", fill=True)
    pdf.ln()

    pdf.set_font("Helvetica", "", 8)
    for _, row in patient_df.iterrows():
        flag = str(row.get("Alerte", ""))
        is_critical = "CRITICAL" in flag
        is_outlier = "Outlier" in flag
        if is_critical:
            pdf.set_text_color(176, 58, 46)
            pdf.set_font("Helvetica", "B", 8)
        elif is_outlier:
            pdf.set_text_color(176, 58, 46)
            pdf.set_font("Helvetica", "", 8)
        else:
            pdf.set_text_color(27, 38, 49)
            pdf.set_font("Helvetica", "", 8)

        ref_range = ""
        if pd.notna(row.get("ref_low")) and pd.notna(row.get("ref_high")):
            ref_range = f"{row['ref_low']}-{row['ref_high']}"
        flag_clean = ("CRITICAL" if is_critical
                      else ("OUTLIER" if is_outlier else ("Normal" if flag else "")))
        values = [
            str(row.get("visit_code", "")), str(row.get("test_code", "")),
            str(row.get("result_value", "")), str(row.get("result_unit", "")),
            ref_range, str(row.get("result_date", "")), flag_clean,
        ]
        for val, width in zip(values, col_widths):
            pdf.cell(width, 6, val[:20], border=1)
        pdf.ln()

    pdf.set_text_color(27, 38, 49)
    pdf.ln(4)

    remarks_df = read_remarks(conn)
    patient_remarks = remarks_df[remarks_df["usubjid"] == usubjid] if not remarks_df.empty else remarks_df
    if patient_remarks is not None and not patient_remarks.empty:
        pdf.set_font("Helvetica", "B", 10)
        pdf.cell(0, 6, "Comments", ln=1)
        pdf.set_font("Helvetica", "", 8)
        for _, r in patient_remarks.iterrows():
            pdf.multi_cell(0, 5, f"- [{r['user_name']}, {r['created_at']}] {r['remark_text']}")
        pdf.ln(2)

    pdf.set_font("Helvetica", "I", 7)
    pdf.set_text_color(120, 130, 140)
    pdf.multi_cell(
        0, 4,
        f"Report generated at (UTC): {generated_at}. Last biological validation by: "
        f"{validator}. This generation is itself recorded in the immutable audit trail "
        f"(21 CFR Part 11 / Annex 11)."
    )

    if password:
        pdf.set_encryption(owner_password=password + "-owner", user_password=password)

    return bytes(pdf.output(dest="S"))
